/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface GeoWebParcelInterface extends utils.Interface {
  contractName: "GeoWebParcel";
  functions: {
    "getLandParcel(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLandParcel",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLandParcel",
    data: BytesLike
  ): Result;

  events: {};
}

export interface GeoWebParcel extends BaseContract {
  contractName: "GeoWebParcel";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GeoWebParcelInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLandParcel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        baseCoordinate: BigNumber;
        path: BigNumber[];
      }
    >;
  };

  getLandParcel(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber[]] & { baseCoordinate: BigNumber; path: BigNumber[] }
  >;

  callStatic: {
    getLandParcel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        baseCoordinate: BigNumber;
        path: BigNumber[];
      }
    >;
  };

  filters: {};

  estimateGas: {
    getLandParcel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLandParcel(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
