name: "CI"
on: ["pull_request"]
jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Run tests"
        run: "yarn tests:run"
