name: "CI"
on:
  workflow_dispatch:
  push:
    branches:
      - "*" # All branches
jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Build"
        run: "yarn build"
      - name: "Run tests"
        run: "yarn tests:run"
