on: ["pull_request"]
name: Test Coveralls
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Build"
        run: "yarn build"
      - name: "Run solidity coverage"
        run: "yarn hardhat coverage"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
