name: "CI"
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Build"
        run: "yarn build"
      - name: "Lint"
        run: "yarn lint"
